"""
Base AI Provider abstraction and structured analysis schemas for MailRecon AI.
"""
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.detectors.base import FindingData
from app.parser.email_parser import ParsedEmailResult


class AIAnalysisResult(BaseModel):
    """
    Structured, grounded forensic intelligence briefing generated by an AI provider.
    All claims must be supported by concrete parsed evidence.
    """
    executive_summary: str = Field(
        ...,
        description="Plain-English executive briefing summarizing the email nature, legitimacy, and risk.",
    )
    attack_vector: str = Field(
        ...,
        description="Primary classification (e.g., 'Business Email Compromise (BEC)', 'Credential Harvesting', 'Benign').",
    )
    threat_actor_tactics: List[str] = Field(
        default_factory=list,
        description="Specific adversary tactics observed (e.g., 'Display Name Spoofing', 'Urgency Coercion').",
    )
    recommended_actions: List[str] = Field(
        default_factory=list,
        description="Actionable incident response and mitigation steps for the security operations team.",
    )
    evidence_citations: List[str] = Field(
        default_factory=list,
        description="Direct citations to observed headers, findings, or body evidence supporting the assessment.",
    )
    is_grounded: bool = Field(
        default=True,
        description="Indicates whether all cited indicators were confirmed present in the case evidence.",
    )
    provider: str = Field(
        default="mock",
        description="The AI provider responsible for generating this analysis ('gemini' or 'mock').",
    )


class BaseAIProvider(ABC):
    """Abstract interface for MailRecon AI intelligence providers."""
    name: str

    @abstractmethod
    async def generate_analysis(
        self, parsed: ParsedEmailResult, findings: List[FindingData]
    ) -> AIAnalysisResult:
        """
        Synthesize parsed email evidence and detector findings into an actionable forensic briefing.
        """
        pass
